make4:
	hspice bhv4.sp > log4 &
	hspice bhv4_z2.sp > log4_z2 &
	hspice bhv4_z3.sp > log4_z3 &
	hspice bhv4_z4.sp > log4_z4 &
	hspice bhv4_z5.sp > log4_z5 &
	hspice bhv4_z6.sp > log4_z6 &
make4_noCp:
	hspice bhv4_noCp.sp > log4_noCp &
	hspice bhv4_z2_noCp.sp > log4_z2_noCp &
	hspice bhv4_z3_noCp.sp > log4_z3_noCp &
	hspice bhv4_z4_noCp.sp > log4_z4_noCp &
	hspice bhv4_z5_noCp.sp > log4_z5_noCp &
	hspice bhv4_z6_noCp.sp > log4_z6_noCp &
make2:
	hspice bhv2.sp > log2 &
	hspice bhv2_z2.sp > log2_z2 &
	hspice bhv2_z3.sp > log2_z3 &
	hspice bhv2_z4.sp > log2_z4 &
	hspice bhv2_z5.sp > log2_z5 &
	hspice bhv2_z6.sp > log2_z6 &
make2_noCp:
	hspice bhv2_noCp.sp > log2_noCp &
	hspice bhv2_z2_noCp.sp > log2_z2_noCp &
	hspice bhv2_z3_noCp.sp > log2_z3_noCp &
	hspice bhv2_z4_noCp.sp > log2_z4_noCp &
	hspice bhv2_z5_noCp.sp > log2_z5_noCp &
	hspice bhv2_z6_noCp.sp > log2_z6_noCp &
make2_10b:
	hspice bhv2_10b.sp > log2_10b &
	hspice bhv2_z2_10b.sp > log2_z2_10b &
	hspice bhv2_z3_10b.sp > log2_z3_10b &
	hspice bhv2_z4_10b.sp > log2_z4_10b &
	hspice bhv2_z5_10b.sp > log2_z5_10b &
	hspice bhv2_z6_10b.sp > log2_z6_10b &
make2_10b_cpx100m:
	hspice bhv2_10b_cpx100m.sp > log2_10b_cpx100m &
	hspice bhv2_z2_10b_cpx100m.sp > log2_z2_10b_cpx100m &
	hspice bhv2_z3_10b_cpx100m.sp > log2_z3_10b_cpx100m &
	hspice bhv2_z4_10b_cpx100m.sp > log2_z4_10b_cpx100m &
	hspice bhv2_z5_10b_cpx100m.sp > log2_z5_10b_cpx100m &
	hspice bhv2_z6_10b_cpx100m.sp > log2_z6_10b_cpx100m &
make2_10b_noCp:
	hspice bhv2_10b_noCp.sp > log2_10b_noCp &
	hspice bhv2_z2_10b_noCp.sp > log2_z2_10b_noCp &
	hspice bhv2_z3_10b_noCp.sp > log2_z3_10b_noCp &
	hspice bhv2_z4_10b_noCp.sp > log2_z4_10b_noCp &
	hspice bhv2_z5_10b_noCp.sp > log2_z5_10b_noCp &
	hspice bhv2_z6_10b_noCp.sp > log2_z6_10b_noCp &
makeall: make4 make4_noCp make2 make2_10b
